services:
  app:
    container_name: sharefin-backend-dev
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    ports:
        - "8000:8000"
    environment:
      - DEBUG=0
    stdin_open: true
    tty: true